plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qbolick.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.qbolick.app'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
}
